version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
    restart: unless-stopped
    command: uvicorn backend.api.main:app --host 0.0.0.0 --port 8000 --reload

  # You can uncomment this section if you want to run Supabase locally
  # supabase:
  #   image: supabase/supabase-local
  #   ports:
  #     - "54321:54321"
  #   volumes:
  #     - supabase-data:/var/lib/postgresql/data
  #     - ./supabase/migrations:/supabase/migrations
  #   environment:
  #     - POSTGRES_PASSWORD=postgres

volumes:
  supabase-data: 